version: "3.8"

services:
    database:
        build: 
            context: ${PWD}/database
        image: typefight-db:1.0
        container_name: typefight-postgresql
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - PGTZ=America/Los_Angeles
        volumes: 
            - typefight-db:/var/lib/postgresql/data
volumes: 
    typefight-db:
        driver: local
        name: typefight-db